server:
  port: 8080
  servlet:
    context-path: /order_food

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_food
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
